baseURL = 'https://ethanlatimergb.github.io/'
languageCode = 'en-gb'
theme = 'my-new-theme'

title = 'Every Day We Stray Further from HEAD'
copyright = 'Ethan Latimer'


[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30


[caches]
  [caches.images]
    dir = ':cacheDir/images'
